# Site settings
# in the templates available like {{ site.myvariable }}.
title: LÊ XUÂN ĐỆ
email: xuandepro@gmail
brand: Lê Xuân Đệ
headline: Inventor, Engineer and Futurist
description: > # Chia sẻ để thành công hơn
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lexuande.github." # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: xuandepro@gmail.com
phone: 0901694150

# Tracking
googleAnalitycsID: UA-83933844-1

